on:
  pull_request

jobs:
  build:
    name: Build
    if: ${{ !startsWith(github.event.pull_request.title, '[CI SKIP]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          check-latest: true
          distribution: 'temurin'
          cache: gradle
      - name: Make Gradlew Executable
        run: chmod +x ./gradlew
      - name: Build & Checkstyle
        run: ./gradlew check remapJar
      - name: Hash Jars
        run: ./gradlew hashLibraries
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/libs/*remapped*