on:
  pull_request

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          check-latest: true
          distribution: 'temurin'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v2
      - name: Build Mod
        run: ./gradlew remapJar
      - name: Hash jars
        run: ./gradlew hashLibraries
      - name: Upload build mod
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/libs/*remapped*