name: Publish artifacts
on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses:  actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          check-latest: true
          cache: gradle
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Read Version
        id: read-version
        run: ./gradlew createTagName && cat ./version >> $GITHUB_OUTPUT
      - name: Generate Changelog
        id: generate-changelog
        run: ./gradlew generateChangelog
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read-version.outputs.version }}
          release_name: ${{ steps.read-version.outputs.version }}
          body_path: CHANGELOG.md
          draft: true
          prerelease: true
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mod Build
          path: build/libs/